version: "3.3"

services:

  postgres_db:
    container_name: postgres
    hostname: postgres
    image: postgres:alpine
    env_file:
        #- ./.env.dev.db
        - ./.env.db.example
    volumes:
      - ./postgres_container/pgdata:/var/lib/postgresql/data
      - ./postgres_container/feedDB.sh:/docker-entrypoint-initdb.d/10-init.sh
      # if you want some data restore, point to your backup
      - ./postgres_container/backups:/db_backup
      # point docker to directory with your config
      #- ./postgres_container/configs:/db_config
    networks:
      - backend
    #ports:
    #  - "15433:5432"
    ports:
      - published: 15433
        target: 5432
        protocol: tcp
        mode: host

  pgadmin:
    image: dpage/pgadmin4:latest
    hostname: pgadmin
    container_name: pgadmin
    restart: always
    env_file:
        #- ./.env.dev.pgadmin
        - ./.env.pgadmin.example
    depends_on:
      - postgres_db
    volumes:
      - ./pgadmin_container/servers.json:/pgadmin4/servers.json
      #- ./pgadmin_container/entrypoint.sh:/docker-entrypoint-initdb.d/10-entrypoint.sh
      - ./pgadmin_container/storage/:/var/lib/pgadmin/storage/
    #ports:
    #  - "8081:80"
    ports:
      - published: 8081
        target: 80
        protocol: tcp
        mode: host
    networks:
      - backend

networks: 
  backend:
    driver: bridge
